version: '3.1'

networks:
  dev-network:

services:
  db:
    image: postgres:14.6-alpine
    container_name: db_for_asyncio
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5429:5432"
    networks:
      dev-network:
        aliases:
          - ${PG_HOST}

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.alembic
    container_name: alembic
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_DB: ${PG_DB}
      WAIT_HOSTS: ${PG_HOST}:${PG_PORT}
    depends_on:
      - db
    networks:
      dev-network:
    volumes:
      - ./:/app

