FROM python:3.11
COPY . .

WORKDIR .

RUN pip install --no-cache-dir -r /alembic/requirements-alembic.txt

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait

ENTRYPOINT /wait && bash /alembic/alembic.sh