"""Initial

Revision ID: 0412ea60cded
Revises: 
Create Date: 2022-12-27 12:25:49.382459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0412ea60cded'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
